server:
  port: 8008


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    enabled: false


wayd:
  kafka:
    address: localhost:9092
    groupId: orchestrator
    producer:
      id: orchestrator-producer
